/** Static asset paths under `public/icons/` (see `public.example/README.md`). */
export const icons = {
  if: '/icons/if.svg',
  sun: '/icons/sun.svg',
  moon: '/icons/moon.svg',
  defaultMode: '/icons/default_mode.svg',
  menu: '/icons/menu.svg',
  close: '/icons/close.svg',
  home: '/icons/home.svg',
  forwardArrow: '/icons/forwardArrow.svg',
  courses: {
    brackets: '/icons/courses/brackets.svg',
    graphMaze: '/icons/courses/graph-maze.svg',
    database: '/icons/courses/database.svg',
    binary: '/icons/courses/binary.svg',
    chart: '/icons/courses/chart.svg',
    lambda: '/icons/courses/lambda.svg',
    memory: '/icons/courses/memory.svg',
    stacks: '/icons/courses/stacks.svg',
    brain: '/icons/courses/brain.svg',
    automation: '/icons/courses/automation.svg',
    codeBlocks: '/icons/courses/code-blocks.svg',
    controller: '/icons/courses/controller.svg',
    sigma: '/icons/courses/sigma.svg',
  },
} as const;
